<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('countries')->delete();
		$countries = array(
      array('code' =>  'AF', 'name' => 'Afganistán'),
      array('code' => 'AX', 'name' => 'Islas Gland'),
      array('code' =>  'AL', 'name' => 'Albania'),
      array('code' =>  'DE', 'name' => 'Alemania'),
      array('code' =>  'AD', 'name' => 'Andorra'),
      array('code' =>  'AO', 'name' => 'Angola'),
      array('code' =>  'AI', 'name' => 'Anguilla'),
      array('code' =>  'AQ', 'name' => 'Antártida'),
      array('code' =>  'AG', 'name' => 'Antigua y Barbuda'),
      array('code' =>  'AN', 'name' => 'Antillas Holandesas'),
      array('code' =>  'SA', 'name' => 'Arabia Saudí'),
      array('code' =>  'DZ', 'name' => 'Argelia'),
      array('code' =>  'AR', 'name' => 'Argentina'),
      array('code' =>  'AM', 'name' => 'Armenia'),
      array('code' =>  'AW', 'name' => 'Aruba'),
      array('code' =>  'AU', 'name' => 'Australia'),
      array('code' =>  'AT', 'name' => 'Austria'),
      array('code' =>  'AZ', 'name' => 'Azerbaiyán'),
      array('code' =>  'BS', 'name' => 'Bahamas'),
      array('code' =>  'BH', 'name' => 'Bahréin'),
      array('code' =>  'BD', 'name' => 'Bangladesh'),
      array('code' =>  'BB', 'name' => 'Barbados'),
      array('code' =>  'BY', 'name' => 'Bielorrusia'),
      array('code' =>  'BE', 'name' => 'Bélgica'),
      array('code' =>  'BZ', 'name' => 'Belice'),
      array('code' =>  'BJ', 'name' => 'Benin'),
      array('code' =>  'BM', 'name' => 'Bermudas'),
      array('code' =>  'BT', 'name' => 'Bhután'),
      array('code' =>  'BO', 'name' => 'Bolivia'),
      array('code' =>  'BA', 'name' => 'Bosnia y Herzegovina'),
      array('code' =>  'BW', 'name' => 'Botsuana'),
      array('code' =>  'BV', 'name' => 'Isla Bouvet'),
      array('code' =>  'BR', 'name' => 'Brasil'),
      array('code' =>  'BN', 'name' => 'Brunéi'),
      array('code' =>  'BG', 'name' => 'Bulgaria'),
      array('code' =>  'BF', 'name' => 'Burkina Faso'),
      array('code' =>  'BI', 'name' => 'Burundi'),
      array('code' =>  'CV', 'name' => 'Cabo Verde'),
      array('code' =>  'KY', 'name' => 'Islas Caimán'),
      array('code' =>  'KH', 'name' => 'Camboya'),
      array('code' =>  'CM', 'name' => 'Camerún'),
      array('code' =>  'CA', 'name' => 'Canadá'),
      array('code' =>  'CF', 'name' => 'República Centroafricana'),
      array('code' =>  'TD', 'name' => 'Chad'),
      array('code' =>  'CZ', 'name' => 'República Checa'),
      array('code' =>  'CL', 'name' => 'Chile'),
      array('code' =>  'CN', 'name' => 'China'),
      array('code' =>  'CY', 'name' => 'Chipre'),
      array('code' =>  'CX', 'name' => 'Isla de Navidad'),
      array('code' =>  'VA', 'name' => 'Ciudad del Vaticano'),
      array('code' =>  'CC', 'name' => 'Islas Cocos'),
      array('code' =>  'CO', 'name' => 'Colombia'),
      array('code' =>  'KM', 'name' => 'Comoras'),
      array('code' =>  'CD', 'name' => 'República Democrática del Congo'),
      array('code' =>  'CG', 'name' => 'Congo'),
      array('code' =>  'CK', 'name' => 'Islas Cook'),
      array('code' =>  'KP', 'name' => 'Corea del Norte'),
      array('code' =>  'KR', 'name' => 'Corea del Sur'),
      array('code' =>  'CI', 'name' => 'Costa de Marfil'),
      array('code' =>  'CR', 'name' => 'Costa Rica'),
      array('code' =>  'HR', 'name' => 'Croacia'),
      array('code' =>  'CU', 'name' => 'Cuba'),
      array('code' =>  'DK', 'name' => 'Dinamarca'),
      array('code' =>  'DM', 'name' => 'Dominica'),
      array('code' =>  'DO', 'name' => 'República Dominicana'),
      array('code' =>  'EC', 'name' => 'Ecuador'),
      array('code' =>  'EG', 'name' => 'Egipto'),
      array('code' =>  'SV', 'name' => 'El Salvador'),
      array('code' =>  'AE', 'name' => 'Emiratos Árabes Unidos'),
      array('code' =>  'ER', 'name' => 'Eritrea'),
      array('code' =>  'SK', 'name' => 'Eslovaquia'),
      array('code' =>  'SI', 'name' => 'Eslovenia'),
      array('code' =>  'ES', 'name' => 'España'),
      array('code' =>  'UM', 'name' => 'Islas ultramarinas de Estados Unidos'),
      array('code' =>  'US', 'name' => 'Estados Unidos'),
      array('code' =>  'EE', 'name' => 'Estonia'),
      array('code' =>  'ET', 'name' => 'Etiopía'),
      array('code' =>  'FO', 'name' => 'Islas Feroe'),
      array('code' =>  'PH', 'name' => 'Filipinas'),
      array('code' =>  'FI', 'name' => 'Finlandia'),
      array('code' =>  'FJ', 'name' => 'Fiyi'),
      array('code' =>  'FR', 'name' => 'Francia'),
      array('code' =>  'GA', 'name' => 'Gabón'),
      array('code' =>  'GM', 'name' => 'Gambia'),
      array('code' =>  'GE', 'name' => 'Georgia'),
      array('code' =>  'GS', 'name' => 'Islas Georgias del Sur y Sandwich del Sur'),
      array('code' =>  'GH', 'name' => 'Ghana'),
      array('code' =>  'GI', 'name' => 'Gibraltar'),
      array('code' =>  'GD', 'name' => 'Granada'),
      array('code' =>  'GR', 'name' => 'Grecia'),
      array('code' =>  'GL', 'name' => 'Groenlandia'),
      array('code' =>  'GP', 'name' => 'Guadalupe'),
      array('code' =>  'GU', 'name' => 'Guam'),
      array('code' =>  'GT', 'name' => 'Guatemala'),
      array('code' =>  'GF', 'name' => 'Guayana Francesa'),
      array('code' =>  'GN', 'name' => 'Guinea'),
      array('code' =>  'GQ', 'name' => 'Guinea Ecuatorial'),
      array('code' =>  'GW', 'name' => 'Guinea-Bissau'),
      array('code' =>  'GY', 'name' => 'Guyana'),
      array('code' =>  'HT', 'name' => 'Haití'),
      array('code' =>  'HM', 'name' => 'Islas Heard y McDonald'),
      array('code' =>  'HN', 'name' => 'Honduras'),
      array('code' =>  'HK', 'name' => 'Hong Kong'),
      array('code' =>  'HU', 'name' => 'Hungría'),
      array('code' =>  'IN', 'name' => 'India'),
      array('code' =>  'ID', 'name' => 'Indonesia'),
      array('code' =>  'IR', 'name' => 'Irán'),
      array('code' =>  'IQ', 'name' => 'Iraq'),
      array('code' =>  'IE', 'name' => 'Irlanda'),
      array('code' =>  'IS', 'name' => 'Islandia'),
      array('code' =>  'IL', 'name' => 'Israel'),
      array('code' =>  'IT', 'name' => 'Italia'),
      array('code' =>  'JM', 'name' => 'Jamaica'),
      array('code' =>  'JP', 'name' => 'Japón'),
      array('code' =>  'JO', 'name' => 'Jordania'),
      array('code' =>  'KZ', 'name' => 'Kazajstán'),
      array('code' =>  'KE', 'name' => 'Kenia'),
      array('code' =>  'KG', 'name' => 'Kirguistán'),
      array('code' =>  'KI', 'name' => 'Kiribati'),
      array('code' =>  'KW', 'name' => 'Kuwait'),
      array('code' =>  'LA', 'name' => 'Laos'),
      array('code' =>  'LS', 'name' => 'Lesotho'),
      array('code' =>  'LV', 'name' => 'Letonia'),
      array('code' =>  'LB', 'name' => 'Líbano'),
      array('code' =>  'LR', 'name' => 'Liberia'),
      array('code' =>  'LY', 'name' => 'Libia'),
      array('code' =>  'LI', 'name' => 'Liechtenstein'),
      array('code' =>  'LT', 'name' => 'Lituania'),
      array('code' =>  'LU', 'name' => 'Luxemburgo'),
      array('code' =>  'MO', 'name' => 'Macao'),
      array('code' =>  'MK', 'name' => 'ARY Macedonia'),
      array('code' =>  'MG', 'name' => 'Madagascar'),
      array('code' =>  'MY', 'name' => 'Malasia'),
      array('code' =>  'MW', 'name' => 'Malawi'),
      array('code' =>  'MV', 'name' => 'Maldivas'),
      array('code' =>  'ML', 'name' => 'Malí'),
      array('code' =>  'MT', 'name' => 'Malta'),
      array('code' =>  'FK', 'name' => 'Islas Malvinas'),
      array('code' =>  'MP', 'name' => 'Islas Marianas del Norte'),
      array('code' =>  'MA', 'name' => 'Marruecos'),
      array('code' =>  'MH', 'name' => 'Islas Marshall'),
      array('code' =>  'MQ', 'name' => 'Martinica'),
      array('code' =>  'MU', 'name' => 'Mauricio'),
      array('code' =>  'MR', 'name' => 'Mauritania'),
      array('code' =>  'YT', 'name' => 'Mayotte'),
      array('code' =>  'MX', 'name' => 'México'),
      array('code' =>  'FM', 'name' => 'Micronesia'),
      array('code' =>  'MD', 'name' => 'Moldavia'),
      array('code' =>  'MC', 'name' => 'Mónaco'),
      array('code' =>  'MN', 'name' => 'Mongolia'),
      array('code' =>  'MS', 'name' => 'Montserrat'),
      array('code' =>  'MZ', 'name' => 'Mozambique'),
      array('code' =>  'MM', 'name' => 'Myanmar'),
      array('code' =>  'NA', 'name' => 'Namibia'),
      array('code' =>  'NR', 'name' => 'Nauru'),
      array('code' =>  'NP', 'name' => 'Nepal'),
      array('code' =>  'NI', 'name' => 'Nicaragua'),
      array('code' =>  'NE', 'name' => 'Níger'),
      array('code' =>  'NG', 'name' => 'Nigeria'),
      array('code' =>  'NU', 'name' => 'Niue'),
      array('code' =>  'NF', 'name' => 'Isla Norfolk'),
      array('code' =>  'NO', 'name' => 'Noruega'),
      array('code' =>  'NC', 'name' => 'Nueva Caledonia'),
      array('code' =>  'NZ', 'name' => 'Nueva Zelanda'),
      array('code' =>  'OM', 'name' => 'Omán'),
      array('code' =>  'NL', 'name' => 'Países Bajos'),
      array('code' =>  'PK', 'name' => 'Pakistán'),
      array('code' =>  'PW', 'name' => 'Palau'),
      array('code' =>  'PS', 'name' => 'Palestina'),
      array('code' =>  'PA', 'name' => 'Panamá'),
      array('code' =>  'PG', 'name' => 'Papúa Nueva Guinea'),
      array('code' =>  'PY', 'name' => 'Paraguay'),
      array('code' =>  'PE', 'name' => 'Perú'),
      array('code' =>  'PN', 'name' => 'Islas Pitcairn'),
      array('code' =>  'PF', 'name' => 'Polinesia Francesa'),
      array('code' =>  'PL', 'name' => 'Polonia'),
      array('code' =>  'PT', 'name' => 'Portugal'),
      array('code' =>  'PR', 'name' => 'Puerto Rico'),
      array('code' =>  'QA', 'name' => 'Qatar'),
      array('code' =>  'GB', 'name' => 'Reino Unido'),
      array('code' =>  'RE', 'name' => 'Reunión'),
      array('code' =>  'RW', 'name' => 'Ruanda'),
      array('code' =>  'RO', 'name' => 'Rumania'),
      array('code' =>  'RU', 'name' => 'Rusia'),
      array('code' =>  'EH', 'name' => 'Sahara Occidental'),
      array('code' =>  'SB', 'name' => 'Islas Salomón'),
      array('code' =>  'WS', 'name' => 'Samoa'),
      array('code' =>  'AS', 'name' => 'Samoa Americana'),
      array('code' =>  'KN', 'name' => 'San Cristóbal y Nevis'),
      array('code' =>  'SM', 'name' => 'San Marino'),
      array('code' =>  'PM', 'name' => 'San Pedro y Miquelón'),
      array('code' =>  'VC', 'name' => 'San Vicente y las Granadinas'),
      array('code' =>  'SH', 'name' => 'Santa Helena'),
      array('code' =>  'LC', 'name' => 'Santa Lucía'),
      array('code' =>  'ST', 'name' => 'Santo Tomé y Príncipe'),
      array('code' =>  'SN', 'name' => 'Senegal'),
      array('code' =>  'CS', 'name' => 'Serbia y Montenegro'),
      array('code' =>  'SC', 'name' => 'Seychelles'),
      array('code' =>  'SL', 'name' => 'Sierra Leona'),
      array('code' =>  'SG', 'name' => 'Singapur'),
      array('code' =>  'SY', 'name' => 'Siria'),
      array('code' =>  'SO', 'name' => 'Somalia'),
      array('code' =>  'LK', 'name' => 'Sri Lanka'),
      array('code' =>  'SZ', 'name' => 'Suazilandia'),
      array('code' =>  'ZA', 'name' => 'Sudáfrica'),
      array('code' =>  'SD', 'name' => 'Sudán'),
      array('code' =>  'SE', 'name' => 'Suecia'),
      array('code' =>  'CH', 'name' => 'Suiza'),
      array('code' =>  'SR', 'name' => 'Surinam'),
      array('code' =>  'SJ', 'name' => 'Svalbard y Jan Mayen'),
      array('code' =>  'TH', 'name' => 'Tailandia'),
      array('code' =>  'TW', 'name' => 'Taiwán'),
      array('code' =>  'TZ', 'name' => 'Tanzania'),
      array('code' =>  'TJ', 'name' => 'Tayikistán'),
      array('code' =>  'IO', 'name' => 'Territorio Británico del Océano Índico'),
      array('code' =>  'TF', 'name' => 'Territorios Australes Franceses'),
      array('code' =>  'TL', 'name' => 'Timor Oriental'),
      array('code' =>  'TG', 'name' => 'Togo'),
      array('code' =>  'TK', 'name' => 'Tokelau'),
      array('code' =>  'TO', 'name' => 'Tonga'),
      array('code' =>  'TT', 'name' => 'Trinidad y Tobago'),
      array('code' =>  'TN', 'name' => 'Túnez'),
      array('code' =>  'TC', 'name' => 'Islas Turcas y Caicos'),
      array('code' =>  'TM', 'name' => 'Turkmenistán'),
      array('code' =>  'TR', 'name' => 'Turquía'),
      array('code' =>  'TV', 'name' => 'Tuvalu'),
      array('code' =>  'UA', 'name' => 'Ucrania'),
      array('code' =>  'UG', 'name' => 'Uganda'),
      array('code' =>  'UY', 'name' => 'Uruguay'),
      array('code' =>  'UZ', 'name' => 'Uzbekistán'),
      array('code' =>  'VU', 'name' => 'Vanuatu'),
      array('code' =>  'VE', 'name' => 'Venezuela'),
      array('code' =>  'VN', 'name' => 'Vietnam'),
      array('code' =>  'VG', 'name' => 'Islas Vírgenes Británicas'),
      array('code' =>  'VI', 'name' => 'Islas Vírgenes de los Estados Unidos'),
      array('code' =>  'WF', 'name' => 'Wallis y Futuna'),
      array('code' =>  'YE', 'name' => 'Yemen'),
      array('code' =>  'DJ', 'name' => 'Yibuti'),
      array('code' =>  'ZM', 'name' => 'Zambia'),
      array('code' =>  'ZW', 'name' => 'Zimbabue')
		);
		DB::table('countries')->insert($countries);
    }
}
